sonar.projectKey=weather-devops
sonar.projectName=weather-devops

sonar.sources=api,web
sonar.tests=api,web/tests

sonar.test.inclusions=api/**/*_test.go,web/tests/**
sonar.exclusions=web/node_modules/**,api/**/*_test.go,web/tests/**

sonar.sourceEncoding=UTF-8