server {
    listen 80;
    server_name _;

    location = /api {
        return 301 /api/;
    }

    location = /hom {
        return 301 /hom/;
    }

    location = /hom/api {
        return 301 /hom/api/;
    }

    location /hom/api/ {
        proxy_pass http://10.20.2.62/;

        proxy_http_version 1.1;
        proxy_set_header Host hom.weather.local;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /hom/static/ {
        proxy_pass http://127.0.0.1:8081/static/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Accept-Encoding "";

        sub_filter_once off;
        sub_filter_types text/html text/css application/javascript text/javascript;
        sub_filter "http://localhost:8002" "/hom/api";
    }

    location /hom/assets/ {
        proxy_pass http://127.0.0.1:8081/assets/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://10.20.2.62/;

        proxy_http_version 1.1;
        proxy_set_header Host prod.weather.local;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /hom/ {
        proxy_pass http://127.0.0.1:8081/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Accept-Encoding "";

        sub_filter_once off;
        sub_filter_types text/html text/css application/javascript text/javascript;
        sub_filter "http://localhost:8002" "/hom/api";
        sub_filter "../static/" "/hom/static/";
        sub_filter "../assets/" "/hom/assets/";
    }

    location / {
        proxy_pass http://127.0.0.1:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Accept-Encoding "";

        sub_filter_once off;
        sub_filter_types text/html text/css application/javascript text/javascript;
        sub_filter "http://localhost:8002" "/api";
    }
}
