server {
    listen 80;
    server_name _;

    location = /api {
        return 301 /api/;
    }

    location /api/ {
        proxy_pass http://10.20.2.62/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Accept-Encoding "";

        sub_filter_once off;
        sub_filter_types text/html text/css application/javascript text/javascript;
        sub_filter "http://localhost:8002" "/api";
    }
}