apiVersion: v1
kind: Service

metadata:
  name: postgres-primary-headless

spec:
  clusterIP: None
  selector:
    app: postgres
    role: primary
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  name: postgres-primary

spec:
  type: ClusterIP
  selector:
    app: postgres
    role: primary
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  name: postgres-read-headless

spec:
  clusterIP: None
  selector:
    app: postgres
    role: read
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  name: postgres-read

spec:
  type: ClusterIP
  selector:
    app: postgres
    role: read
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
