apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-read

spec:
  serviceName: postgres-read-headless
  replicas: 2
  selector:
    matchLabels:
      app: postgres
      role: read
  template:
    metadata:
      labels:
        app: postgres
        role: read
    spec:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: postgres
          image: bitnamilegacy/postgresql:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: slave
            - name: POSTGRESQL_MASTER_HOST
              value: postgres-primary
            - name: POSTGRESQL_MASTER_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRESQL_REPLICATION_USER
              value: repl_user
            - name: POSTGRESQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: replication-password

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: postgres-read-data
              mountPath: /bitnami/postgresql

  volumeClaimTemplates:
    - metadata:
        name: postgres-read-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
