apiVersion: apps/v1
kind: Deployment

metadata:
  name: weather-api
  namespace: weather-app

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: weather-api

  template:
    metadata:
      labels:
        app: weather-api

    spec:
      containers:
        - name: weather-api
          image: mainiere/weather-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8002

          volumeMounts:
            - name: weather-api-env
              mountPath: /app/.env
              subPath: .env
              readOnly: true

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 20

      volumes:
        - name: weather-api-env
          secret:
            secretName: weather-api-secret
