apiVersion: v1
kind: ResourceQuota

metadata:
  name: weather-quota
  namespace: weather-app

spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 2Gi
