- name: Aplicacao dos manifests do Kubernetes no cluster AKS
  hosts: local
  connection: local

  vars:
    project_root: "{{ playbook_dir }}/../../.."

  tasks:
    - name: Verificar acesso ao AKS
      shell: kubectl get nodes

    - name: Aplicar namespace
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/namespace.yaml"

    - name: Aplicar ResourceQuota
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/resource-quota.yaml"

    - name: Aplicar LimitRange
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/limit-range.yaml"

    - name: Aplicar Secret da API
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/api-secret.yaml"

    - name: Aplicar manifests do banco de dados
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/database"

    - name: Aplicar Deployment da API
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/deployment.yaml"

    - name: Aplicar Service da API
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/service.yaml"

    - name: Aplicar HPA da API
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/hpa.yaml"

    - name: Aplicar Ingress da API
      shell: kubectl apply -f "{{ project_root }}/infra/kubernetes/ingress.yaml"

    - name: Verificar pods do namespace weather-app
      shell: kubectl get pods -n weather-app
      register: pods_result

    - name: Exibir pods criados
      debug:
        var: pods_result.stdout_lines

    - name: Verificar ingress da API
      shell: kubectl get ingress -n weather-app
      register: ingress_result

    - name: Exibir ingress criado
      debug:
        var: ingress_result.stdout_lines

    - name: Verificar services do namespace weather-app
      shell: kubectl get svc -n weather-app
      register: services_result

    - name: Exibir services criados
      debug:
        var: services_result.stdout_lines

    - name: Validar health check da API no AKS
      shell: kubectl run curl-test -n weather-app --rm -i --image=curlimages/curl --restart=Never -- curl -s http://weather-api:8002/health
      register: api_health_result

    - name: Exibir resultado do health check
      debug:
        var: api_health_result.stdout_lines
